repos:

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-mod-tidy

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.19
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-frontmatter
    - mdformat-footnote
    - mdformat-toc
    - mdformat-gfm-alerts
